
#!/bin/bash
#
# Title:      Filebot for PGBlitz (OAuth security)
# Author(s):  fla243
# URL:        https://pgblitz.com & https://github.com/fla243/Apps-Community
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'filebot'
        intport: '5800'
        extport: '5803'
        intport2: '5902'
        extport2: '5903'
        intport3: '3129'
        extport3: '3123'
        image: 'filebot-mod'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

    - name: 'Including plugins'
      include_tasks: '/opt/communityapps/apps/_plugins.yml'

    - name: 'Ini Check'
      stat:
        path: /opt/appdata/{{pgrole}}/core.conf
      register: inicheck

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}},{{tldset}}'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}:/config'
          - '/mnt:/storage'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          UID: '1000'
          GID: '1000'

    # BUILD CUSTOM IMAGE ##########################################################
    - name: 'Building modded {{pgrole}} image'
      docker_image: >
          name='{{image}}'
          path=templates/filebot
          state=present
          build:
            args:
              - 'FILEBOT_VERSION:4.8.6'

    # COPY LICENSE FILE
    - name: 'Copy filebot license file'
      command: cp templates/filebot/license.psm /opt/appdata/{{pgrole}}/

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
       # pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'

##PG-Community
